name = "EasyFITS"
uuid = "a977f4a2-36a7-4172-89e7-19c2726f82e5"
authors = ["Éric Thiébaut <https://github.com/emmt>"]
version = "0.6.1"

[deps]
CFITSIO_jll = "b3e40c51-02ae-5482-8a39-3ace5868dcf4"
Clang = "40e3b903-d033-50b4-a0cc-940c62c95e31"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FITSHeaders = "8163a04c-c153-4fb1-a498-3402381ec208"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
TypeUtils = "c3b1956e-8857-4d84-9b79-890df85b1e67"

[compat]
CFITSIO_jll = "4.3"
Clang = "0.14, 0.15, 0.16, 0.17, 0.18"
FITSHeaders = "0.4"
Requires = "1.3"
TOML = "1.0"
TypeUtils = "0.2, 0.3, 1"
julia = "1.6"

[extras]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "DataFrames"]
