name = "EasyFITS"
uuid = "a977f4a2-36a7-4172-89e7-19c2726f82e5"
authors = ["Éric Thiébaut <eric.thiebaut@univ-lyon1.fr>"]
version = "0.2.0"

[deps]
CFITSIO = "3b1b4be9-1499-4b22-8d78-7db3344d1961"
FITSIO = "525bcba6-941b-5504-bd06-fd0dc1a4d2eb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "^1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
